### ISSUE TITLE
[Minor Bug] Autocomplete on Add

### ISSUE THREAD

**Issue by freesoup** [CS2103AUG2017-W13-B3/main#105]
<img width="960" alt="problem 1" src="https://user-images.githubusercontent.com/28558100/32362948-bada320a-c0a7-11e7-87e5-461e7ed2d4ec.png">
Minor Issue with add auto complete.

Steps
1) Add da
2) suggests "Add david"
3) Adding david will give wrong format.

**Comment by newalter** [comment]
solved
