### ISSUE TITLE
[Minor Text Change] When adding the suggested format should include m/ tags

### ISSUE THREAD

**Issue by freesoup** [CS2103AUG2017-W13-B3/main#106]
![problem 2](https://user-images.githubusercontent.com/28558100/32363015-12fee1c4-c0a8-11e7-8fe2-1d88a03c05ea.JPG)

Format does not include m/ Field
However Examples show m/ Field.

Way to recreate problem
Type an invalid add command.

**Comment by newalter** [comment]
solved
