### ISSUE TITLE
[General Improvement] Display more errors

### ISSUE THREAD

**Issue by LauY99** [CS2103AUG2017-W13-B3/main#109]
For most illegal values like resizing to a very small window, invalid date and time, etc. The application ignores (or opt for the closest valid value) instead of displaying an error message stating that the user is wrong.
Examples that I have found are:
resize 2 3 --> A window clearly larger than 2*3
edit 1 m/2018-02-29 12-00 --> Add the meeting as 2018-02-28 12:00

**Comment by newalter** [comment]
solved
