### ISSUE TITLE
[Bug] Resizing to 0 0 does nothing.

### ISSUE THREAD

**Issue by freesoup** [CS2103AUG2017-W13-B3/main#99]
![bug 3](https://user-images.githubusercontent.com/28558100/32362688-3b3ee49c-c0a6-11e7-9612-c7bceba9192f.JPG)

1) type resize 0 0
2) type resize 0 x
3) type resize x 0
(x being a random number lesser than resolution)

Fields that are 0 do not have effect on the screen size.

**Comment by newalter** [comment]
solved
